apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-app
          # 🔹 Updated image version
          image: your-dockerhub-username/messaging-app:2.0
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: messaging-app-blue
#   labels:
#     app: messaging-app
#     version: blue
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: messaging-app
#       version: blue
#   template:
#     metadata:
#       labels:
#         app: messaging-app
#         version: blue
#     spec:
#       containers:
#         - name: messaging-app
#           # ❗ replace with your real image (blue/v1)
#           image: your-dockerhub-username/messaging-app:v1
#           ports:
#             - containerPort: 8000
#           env:
#             - name: DJANGO_SETTINGS_MODULE
#               value: messaging_app.settings
